title: Alexander Vonderau
description: IT Graduate | Game Developer | Technical Builder
url: "https://alexjvon.github.io"
baseurl: "/website"

links:
  github: "https://github.com/alexjvon"
  linkedin: "https://linkedin.com/in/yourusername"
  itch: "https://yourname.itch.io"
  email: "your.email@example.com"

exclude:
  - README.md
  - LICENSE
  - .gitignore